export const categories = ['Beach', 'Park', 'Restaurant', 'Photo Spot', 'Family Activity', 'Nature'];

export const destinations = [
  {
    id: 1,
    name: 'Flagler Avenue Beach Approach',
    slug: 'flagler-avenue-beach-approach',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Beach',
    description: 'The classic entry point for a first beach walk, morning coffee, and colorful street-to-sand photos.',
    latitude: 29.0387,
    longitude: -80.8958,
    featuredImage: '/photos/flager-avenue/hero-flager-avenue.jpg',
    gallery: [
      '/photos/flager-avenue/flager-avenue2.jpg',
      '/photos/flager-avenue/flager-avenue3.jpg',
      '/photos/flager-avenue/flager-avenue4.jpg',
      '/photos/flager-avenue/flager-avenue5.jpg',
      '/photos/flager-avenue/hero-flager-avenue.jpg',
    ],
    parking: 'Metered street parking and nearby public lots.',
    bestTime: 'Sunrise or the first hour after breakfast.',
    photoTip: 'Frame the approach signs with pastel sky and early beach traffic.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 2,
    name: 'Smyrna Dunes Park',
    slug: 'smyrna-dunes-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Beach',
    description: 'A coastal park with elevated boardwalks, inlet views, dune habitat, fishing areas, and a designated dog-friendly beach section.',
    address: '2995 N Peninsula Ave, New Smyrna Beach, FL 32169',
    latitude: 29.0654,
    longitude: -80.9149,
    featuredImage: '/photos/smyrna-dunes-park/dunes_hero.JPG',
    gallery: [
      '/photos/smyrna-dunes-park/dunes2.JPG',
      '/photos/smyrna-dunes-park/dunes3.JPG',
      '/photos/smyrna-dunes-park/dunes4.JPG',
      '/photos/smyrna-dunes-park/dunes5.JPG',
      '/photos/smyrna-dunes-park/dunes6.JPG',
      '/photos/smyrna-dunes-park/dunes_hero.JPG',
    ],
    imageAltText: {
      '/photos/smyrna-dunes-park/dunes2.JPG': 'Smyrna Dunes Park boardwalk crossing coastal dune habitat.',
      '/photos/smyrna-dunes-park/dunes3.JPG': 'Sandy path and shoreline vegetation at Smyrna Dunes Park.',
      '/photos/smyrna-dunes-park/dunes4.JPG': 'Beach access and dune fencing at Smyrna Dunes Park.',
      '/photos/smyrna-dunes-park/dunes5.JPG': 'Wide beach and dune landscape at Smyrna Dunes Park.',
      '/photos/smyrna-dunes-park/dunes6.JPG': 'Coastal view from the Smyrna Dunes Park boardwalk.',
      '/photos/smyrna-dunes-park/dunes_hero.JPG': 'Golden ocean light over the beach at Smyrna Dunes Park.',
    },
    parking: 'On-site parking is available with a $10 per vehicle inlet park fee; the lot can fill on weekends and holidays.',
    bestTime: 'Early morning on weekdays for cooler weather, easier parking, and quieter boardwalk views.',
    photoTip: 'Use the boardwalk curves as leading lines, then look for layered inlet, dune, and shoreline views.',
    duration: '1-2 hr',
    published: true,
  },
  {
    id: 3,
    name: 'Canal Street Historic District',
    slug: 'canal-street-historic-district',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Photo Spot',
    description: 'Historic storefronts, murals, boutiques, and walkable details for relaxed street photography.',
    latitude: 29.0252,
    longitude: -80.9206,
    featuredImage: '/photos/canal-st-historic/hero-canal-st.jpg',
    gallery: [
      '/photos/canal-st-historic/canalst-2.JPG',
      '/photos/canal-st-historic/canalst-3.jpg',
      '/photos/canal-st-historic/canalst-4.JPG',
      '/photos/canal-st-historic/canalst-5.jpg',
      '/photos/canal-st-historic/hero-canal-st.jpg',
    ],
    parking: 'Free public lots and street parking nearby.',
    bestTime: 'Late afternoon when storefronts catch warm light.',
    photoTip: 'Capture detail shots of signs, windows, brick, and sidewalk texture.',
    duration: '1-2 hr',
    published: true,
  },
  {
    id: 4,
    name: 'Old Fort Park',
    slug: 'old-fort-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Park',
    description: 'A quiet historic site near downtown with shaded paths and old stonework textures.',
    latitude: 29.0258,
    longitude: -80.919,
    featuredImage: '/photos/old-fort-park/hero-old-fort.jpg',
    gallery: [
      '/photos/old-fort-park/old-fort2.jpg',
      '/photos/old-fort-park/old-fort3.jpg',
      '/photos/old-fort-park/old-fort4.jpg',
      '/photos/old-fort-park/old-fort5.jpg',
      '/photos/old-fort-park/hero-old-fort.jpg',
    ],
    parking: 'Street parking around the park.',
    bestTime: 'Morning shade or golden hour.',
    photoTip: 'Look for contrast between stone, moss, trees, and sky.',
    duration: '30-60 min',
    published: true,
  },
  {
    id: 5,
    name: 'Riverside Park',
    slug: 'riverside-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Family Activity',
    description: 'A riverfront green space with playground areas, paths, events, and Indian River views.',
    latitude: 29.0236,
    longitude: -80.9182,
    featuredImage: '/photos/riverside-park/hero-riverside.jpg',
    gallery: [
      '/photos/riverside-park/riverside2.JPG',
      '/photos/riverside-park/riverside3.JPG',
      '/photos/riverside-park/riverside4.JPG',
      '/photos/riverside-park/riverside5.JPG',
      '/photos/riverside-park/hero-riverside.jpg',
    ],
    parking: 'Free parking around Canal Street and Riverside Drive.',
    bestTime: 'Sunset for river reflections.',
    photoTip: 'Shoot low across the grass toward the water for layered compositions.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 6,
    name: 'Mary McLeod Bethune Beach Park',
    slug: 'mary-mcleod-bethune-beach-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Beach',
    description: 'A quieter south beach access with oceanfront space and lagoon-side options nearby.',
    mapQuery: '6656 S Atlantic Ave, New Smyrna Beach, FL 32169',
    latitude: 28.9418,
    longitude: -80.8384,
    featuredImage: '/photos/mary-mcleod-bethune-beach-park/mary-hero.JPG',
    gallery: [
      '/photos/mary-mcleod-bethune-beach-park/mary2.JPG',
      '/photos/mary-mcleod-bethune-beach-park/mary3.JPG',
      '/photos/mary-mcleod-bethune-beach-park/mary4.JPG',
      '/photos/mary-mcleod-bethune-beach-park/mary5.JPG',
      '/photos/mary-mcleod-bethune-beach-park/mary6.JPG',
      '/photos/mary-mcleod-bethune-beach-park/mary-hero.JPG',
    ],
    parking: 'Public parking with beach access.',
    bestTime: 'Weekday mornings for a calmer visit.',
    photoTip: 'Bring a longer lens for shorebirds and soft wave detail.',
    duration: '1-2 hr',
    published: true,
  },
  {
    id: 7,
    name: "JB's Fish Camp",
    slug: 'jbs-fish-camp',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Restaurant',
    description: 'A casual waterside seafood stop near the lagoon, popular after beach and kayak trips.',
    latitude: 28.9336,
    longitude: -80.8497,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    parking: 'On-site restaurant parking.',
    bestTime: 'Late lunch or sunset dinner.',
    photoTip: 'Photograph dock details and plates near window light.',
    duration: '1-1.5 hr',
    published: false,
  },
  {
    id: 8,
    name: 'Indian River Lagoon Park',
    slug: 'indian-river-lagoon-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Nature',
    description: 'A low-key park for lagoon views, short walks, birds, and slower coastal moments.',
    mapQuery: '2437+VW New Smyrna Beach, Florida',
    latitude: 28.9905,
    longitude: -80.8742,
    featuredImage: '/photos/indian-river-lagoon-park/indian_hero.JPG',
    gallery: [
      '/photos/indian-river-lagoon-park/indian2.JPG',
      '/photos/indian-river-lagoon-park/indian3.JPG',
      '/photos/indian-river-lagoon-park/indian4.JPG',
      '/photos/indian-river-lagoon-park/indian5.JPG',
      '/photos/indian-river-lagoon-park/indian6.JPG',
      '/photos/indian-river-lagoon-park/indian_hero.JPG',
    ],
    parking: 'Small on-site parking area.',
    bestTime: 'Morning for wildlife and softer reflections.',
    photoTip: 'Use reeds and mangroves to frame the water.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 9,
    name: 'The Garlic',
    slug: 'the-garlic',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Restaurant',
    description: 'A lush, atmospheric dinner spot known for garden paths, low light, and date-night energy.',
    latitude: 29.0432,
    longitude: -80.9004,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    parking: 'On-site and nearby parking, busiest at dinner.',
    bestTime: 'Blue hour before peak dinner rush.',
    photoTip: 'Capture warm lights through greenery before going inside.',
    duration: '1.5-2 hr',
    published: false,
  },
  {
    id: 10,
    name: "Norwood's Treehouse",
    slug: 'norwoods-treehouse',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Restaurant',
    description: 'A memorable restaurant setting with elevated seating, coastal character, and group-friendly energy.',
    latitude: 29.0405,
    longitude: -80.9007,
    featuredImage: '/photos/norwoods-restaurant/hero-norwoods.jpg',
    gallery: [
      '/photos/norwoods-restaurant/norwoods2.jpg',
      '/photos/norwoods-restaurant/norwoods3.jpg',
      '/photos/norwoods-restaurant/norwoods4.jpg',
      '/photos/norwoods-restaurant/norwoods5.jpg',
      '/photos/norwoods-restaurant/hero-norwoods.jpg',
    ],
    parking: 'Restaurant parking available nearby.',
    bestTime: 'Early dinner to catch ambient light.',
    photoTip: 'Shoot vertical frames that show height, stairs, and greenery.',
    duration: '1.5-2 hr',
    published: true,
  },
  {
    id: 11,
    name: 'Third Wave Cafe',
    slug: 'third-wave-cafe',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Restaurant',
    description: 'A cozy cafe and garden-style stop close to Flagler Avenue for brunch, coffee, and evening bites.',
    latitude: 29.0399,
    longitude: -80.9001,
    featuredImage: '/photos/thirdwave-restaurant/hero-thirdwave.JPG',
    gallery: [
      '/photos/thirdwave-restaurant/thirdwave2.JPG',
      '/photos/thirdwave-restaurant/thirdwave3.jpg',
      '/photos/thirdwave-restaurant/thirdwave4.jpg',
      '/photos/thirdwave-restaurant/thirdwave5.JPG',
      '/photos/thirdwave-restaurant/hero-thirdwave.JPG',
    ],
    parking: 'Street parking around Flagler Avenue.',
    bestTime: 'Brunch for bright table photos.',
    photoTip: 'Use shaded patio light for food and portrait shots.',
    duration: '1 hr',
    published: true,
  },
  {
    id: 13,
    name: '27th Avenue Beachfront Park',
    slug: '27th-avenue-beachfront-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Family Activity',
    description: 'Beach access with picnic areas, restrooms, and a practical setup for family beach time.',
    latitude: 29.0107,
    longitude: -80.8815,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    parking: 'Public parking lot by the beach.',
    bestTime: 'Morning before the sand heats up.',
    photoTip: 'Capture candid family moments from the dune crossover.',
    duration: '1-3 hr',
    published: false,
  },
  {
    id: 14,
    name: 'Esther Street Beachfront Park',
    slug: 'esther-street-beachfront-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Beach',
    description: 'A central beach access close to Flagler Avenue with easy walks to food and shops.',
    latitude: 29.0401,
    longitude: -80.8965,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    parking: 'Limited street parking and nearby paid options.',
    bestTime: 'Sunrise and late afternoon.',
    photoTip: 'Use footprints and tide patterns to add foreground interest.',
    duration: '45-120 min',
    published: false,
  },
  {
    id: 17,
    name: 'Buena Vista Park',
    slug: 'buena-vista-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Park',
    description: 'A simple riverfront park with benches, boat activity, and a slower local rhythm.',
    latitude: 29.033,
    longitude: -80.9132,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    parking: 'Small public parking areas nearby.',
    bestTime: 'Golden hour facing the water.',
    photoTip: 'Use benches and railings as foreground anchors.',
    duration: '30-60 min',
    published: false,
  },
  {
    id: 19,
    name: 'Sugar Mill Ruins',
    slug: 'sugar-mill-ruins',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Nature',
    description: 'Historic ruins wrapped in greenery, ideal for texture studies and moody natural-light photos.',
    address: '600 Mission Dr, New Smyrna Beach, FL 32168',
    latitude: 29.0308889,
    longitude: -80.9711111,
    featuredImage: '/photos/plantation-sugar-mill-ruins/hero-ruins.JPG',
    gallery: [
      '/photos/plantation-sugar-mill-ruins/sugar-mill-ruins2.JPG',
      '/photos/plantation-sugar-mill-ruins/sugar-mill-ruins3.JPG',
      '/photos/plantation-sugar-mill-ruins/sugar-mill-ruins4.JPG',
      '/photos/plantation-sugar-mill-ruins/sugar-mill-ruins5.JPG',
      '/photos/plantation-sugar-mill-ruins/hero-ruins.JPG',
    ],
    parking: 'Small free parking area.',
    bestTime: 'Overcast afternoons or early light.',
    photoTip: 'Expose for stone texture and let the background fall darker.',
    duration: '30-60 min',
    published: true,
  },
  {
    id: 20,
    name: 'Turtle Mound',
    slug: 'turtle-mound',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Nature',
    description: 'A scenic mound walk south of town with sweeping lagoon and barrier island views.',
    mapQuery: 'W5JF+5P New Smyrna Beach, Florida',
    latitude: 28.9289,
    longitude: -80.8242,
    featuredImage: '/photos/turtle-mound/turtle-hero.JPG',
    gallery: [
      '/photos/turtle-mound/turtle2.JPG',
      '/photos/turtle-mound/turtle3.JPG',
      '/photos/turtle-mound/turtle4.JPG',
      '/photos/turtle-mound/turtle5.JPG',
      '/photos/turtle-mound/turtle6.JPG',
      '/photos/turtle-mound/turtle-hero.JPG',
    ],
    parking: 'National seashore parking area; check current access rules.',
    bestTime: 'Morning for lower heat and clearer views.',
    photoTip: 'Shoot wide from the overlook to show the curve of the coast.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 21,
    name: 'Grayce K. Barck North Beach Community Park',
    slug: 'grayce-k-barck-north-beach-community-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Park',
    description: 'A quiet north beach community park for shaded breaks, neighborhood walks, and easy coastal photos.',
    latitude: 29.055,
    longitude: -80.907,
    featuredImage: '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    gallery: [
      '/photos/grayce-kenemer-barck-north-beach/grace-kenemer2.jpg',
      '/photos/grayce-kenemer-barck-north-beach/grace-kenemer3.jpg',
      '/photos/grayce-kenemer-barck-north-beach/grace-kenemer4.jpg',
      '/photos/grayce-kenemer-barck-north-beach/grace-kenemer5.jpg',
      '/photos/grayce-kenemer-barck-north-beach/hero-beach.jpg',
    ],
    parking: 'Neighborhood-style public parking nearby; confirm posted signs before leaving the car.',
    bestTime: 'Early morning or late afternoon for softer light and a quieter visit.',
    photoTip: 'Frame palms, paths, and beachside textures to give the park a local, lived-in feel.',
    duration: '30-60 min',
    published: true,
  },
  {
    id: 22,
    name: 'Emory L. Bennett Park',
    slug: 'emory-l-bennett-park',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Park',
    description: 'A neighborhood park stop with open green space, simple facilities, and a relaxed local pace.',
    latitude: 29.019,
    longitude: -80.927,
    featuredImage: '/photos/emory-l-bennett-park/hero-emory.jpg',
    gallery: [
      '/photos/emory-l-bennett-park/emory2.jpg',
      '/photos/emory-l-bennett-park/emory3.jpg',
      '/photos/emory-l-bennett-park/emory4.jpg',
      '/photos/emory-l-bennett-park/emory5.jpg',
      '/photos/emory-l-bennett-park/hero-emory.jpg',
    ],
    parking: 'Small public parking areas nearby; check posted access and park-hour signs.',
    bestTime: 'Morning shade or golden hour when the park feels calmest.',
    photoTip: 'Use trees, benches, and walking paths as simple foreground anchors.',
    duration: '30-60 min',
    published: true,
  },
  {
    id: 23,
    name: 'The Eldora Statehouse',
    slug: 'the-eldora-statehouse',
    city: 'New Smyrna Beach',
    state: 'FL',
    category: 'Photo Spot',
    description: 'A remote historic house and former Eldora village landmark tucked inside Canaveral National Seashore.',
    mapQuery: 'W55H+JJ New Smyrna Beach, Florida',
    latitude: 28.90917,
    longitude: -80.81972,
    featuredImage: '/photos/the-eldora-statehouse/eldora-hero.JPG',
    gallery: [
      '/photos/the-eldora-statehouse/eldora2.JPG',
      '/photos/the-eldora-statehouse/eldora3.JPG',
      '/photos/the-eldora-statehouse/eldora4.JPG',
      '/photos/the-eldora-statehouse/eldora5.JPG',
      '/photos/the-eldora-statehouse/eldora6.JPG',
      '/photos/the-eldora-statehouse/eldora-hero.JPG',
    ],
    parking: 'Canaveral National Seashore access parking nearby; check current park hours and entrance rules.',
    bestTime: 'Morning or late afternoon when the drive and historic grounds feel quietest.',
    photoTip: 'Frame the house with surrounding trees and weathered details to show its old-Florida setting.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 24,
    name: 'Dunlawton Sugar Mill Gardens',
    slug: 'dunlawton-sugar-mill-gardens',
    city: 'Port Orange',
    state: 'FL',
    category: 'Nature',
    description: 'A quiet botanical garden with historic sugar mill ruins, shaded paths, native plants, butterflies, and old-Florida texture.',
    address: '950 Old Sugar Mill Road, Port Orange, FL 32129',
    latitude: 29.1416,
    longitude: -81.0071,
    featuredImage: '/photos/dunlawton-sugar-mill-gardens/sugar_hero.JPG',
    gallery: [
      '/photos/dunlawton-sugar-mill-gardens/sugar2.JPG',
      '/photos/dunlawton-sugar-mill-gardens/sugar3.JPG',
      '/photos/dunlawton-sugar-mill-gardens/sugar4.JPG',
      '/photos/dunlawton-sugar-mill-gardens/sugar5.JPG',
      '/photos/dunlawton-sugar-mill-gardens/sugar6.JPG',
      '/photos/dunlawton-sugar-mill-gardens/sugar_hero.JPG',
    ],
    imageAltText: {
      '/photos/dunlawton-sugar-mill-gardens/sugar2.JPG': 'Garden path through dense greenery at Dunlawton Sugar Mill Gardens.',
      '/photos/dunlawton-sugar-mill-gardens/sugar3.JPG': 'Historic stonework and tropical plants at Dunlawton Sugar Mill Gardens.',
      '/photos/dunlawton-sugar-mill-gardens/sugar4.JPG': 'Shaded botanical garden details at Dunlawton Sugar Mill Gardens.',
      '/photos/dunlawton-sugar-mill-gardens/sugar5.JPG': 'Old sugar mill ruins surrounded by plants at Dunlawton Sugar Mill Gardens.',
      '/photos/dunlawton-sugar-mill-gardens/sugar6.JPG': 'Close view of garden foliage at Dunlawton Sugar Mill Gardens.',
      '/photos/dunlawton-sugar-mill-gardens/sugar_hero.JPG': 'Entrance gate beneath live oaks at Dunlawton Sugar Mill Gardens.',
    },
    parking: 'Small on-site parking area; picnicking, food, snacks, and drinks are not allowed inside the gardens.',
    bestTime: 'Morning for softer garden light, cooler paths, and more comfortable walking.',
    photoTip: 'Look for natural frames around the ruins, flowers, pathways, and shaded garden details.',
    duration: '45-90 min',
    published: true,
  },
  {
    id: 25,
    name: 'Riverwalk Park',
    slug: 'riverwalk-park-port-orange',
    city: 'Port Orange',
    state: 'FL',
    category: 'Family Activity',
    description: 'A riverfront Port Orange park with walking paths, playground areas, open lawn, picnic space, kayak access, and Halifax River views.',
    address: '3459 S Ridgewood Avenue, Port Orange, FL 32129',
    latitude: 29.1486,
    longitude: -80.9888,
    featuredImage: '/photos/riverwalk-park/river_hero.JPG',
    gallery: [
      '/photos/riverwalk-park/river2.JPG',
      '/photos/riverwalk-park/river3.JPG',
      '/photos/riverwalk-park/river4.JPG',
      '/photos/riverwalk-park/river5.JPG',
      '/photos/riverwalk-park/river6.JPG',
      '/photos/riverwalk-park/river_hero.JPG',
    ],
    imageAltText: {
      '/photos/riverwalk-park/river2.JPG': 'Riverwalk Park pathway and lawn beside the Halifax River.',
      '/photos/riverwalk-park/river3.JPG': 'Playground and open recreation area at Riverwalk Park.',
      '/photos/riverwalk-park/river4.JPG': 'Riverfront promenade and palm trees at Riverwalk Park.',
      '/photos/riverwalk-park/river5.JPG': 'Picnic and pavilion area at Riverwalk Park in Port Orange.',
      '/photos/riverwalk-park/river6.JPG': 'Waterfront view from Riverwalk Park toward the Halifax River.',
      '/photos/riverwalk-park/river_hero.JPG': 'Palm-lined Riverwalk Park waterfront reflected in the Halifax River.',
    },
    parking: 'Plenty of parking nearby, with restrooms, picnic tables, pavilions, and barbecue grills available in the park.',
    bestTime: 'Late afternoon for river light, family play time, and a comfortable walk along the waterfront.',
    photoTip: 'Frame the riverwalk, playground energy, and open lawn against the Halifax River for a relaxed local feel.',
    duration: '1-2 hr',
    published: true,
  },
  {
    id: 26,
    name: 'Spruce Creek Park',
    slug: 'spruce-creek-park',
    city: 'Port Orange',
    state: 'FL',
    category: 'Nature',
    description: 'A nature-focused park with boardwalks, more than three miles of trails, marsh views, a canoe launch, and an observation tower.',
    address: '6250 Ridgewood Avenue, Port Orange, FL 32127',
    latitude: 29.0945,
    longitude: -80.9723,
    featuredImage: '/photos/spruce-creek-park/spruce_hero.JPG',
    gallery: [
      '/photos/spruce-creek-park/spruce2.JPG',
      '/photos/spruce-creek-park/spruce3.JPG',
      '/photos/spruce-creek-park/spruce4.JPG',
      '/photos/spruce-creek-park/spruce5.JPG',
      '/photos/spruce-creek-park/spruce6.JPG',
      '/photos/spruce-creek-park/spruce_hero.JPG',
    ],
    imageAltText: {
      '/photos/spruce-creek-park/spruce2.JPG': 'Wooded trail entrance at Spruce Creek Park in Port Orange.',
      '/photos/spruce-creek-park/spruce3.JPG': 'Marsh and water view from Spruce Creek Park.',
      '/photos/spruce-creek-park/spruce4.JPG': 'Natural trail and palms at Spruce Creek Park.',
      '/photos/spruce-creek-park/spruce5.JPG': 'Observation area and greenery at Spruce Creek Park.',
      '/photos/spruce-creek-park/spruce6.JPG': 'Boardwalk railing and creekside vegetation at Spruce Creek Park.',
      '/photos/spruce-creek-park/spruce_hero.JPG': 'Wooden boardwalk leading through palms at Spruce Creek Park.',
    },
    parking: 'Medium-size parking area with restroom access near the trailhead and picnic pavilion.',
    bestTime: 'Morning or late afternoon for cooler hiking conditions, bird activity, and softer marsh light.',
    photoTip: 'Bring a wider lens for boardwalk scenes and a longer lens for birds, marsh details, and views from the tower.',
    duration: '1-2 hr',
    published: true,
  },
];

export const publishedDestinations = destinations.filter((destination) => destination.published);

export function getDestination(slug) {
  return destinations.find((destination) => destination.slug === slug);
}
